#PBS -N neb
#PBS -l nodes=1:ppn=42
#PBS -l walltime=24:00:00
#PBS -q fast
#PBS -V
#PBS -S /bin/bash

module load intel/2020.1.217

NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`

cat $PBS_NODEFILE > /tmp/nodefile.$$
cd $PBS_O_WORKDIR
ulimit -s unlimited

EXEC=/home/changruiwang-ICME/Software/vasp-vtst/bin/vasp_std
mpirun -machinefile $PBS_NODEFILE -np $NP $EXEC > output
