#PBS -N openmx
#PBS -l nodes=1:ppn=32
#PBS -l walltime=600:00:00
#PBS -q manycores
#PBS -V
#PBS -S /bin/bash 
          
module load intel/2020.1.217

NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`
    
cat $PBS_NODEFILE > /tmp/nodefile.$$
cd $PBS_O_WORKDIR
ulimit -s unlimited

EXEC=/home/changruiwang-ICME/Software/openmx3.9/work/openmx
mpirun -machinefile $PBS_NODEFILE -np $NP $EXEC openmx.dat > output

