#!/bin/sh
#将coord.inc和DIMER_VECTOR的振动模式可视化
#以确认dimer算法的优化目标是否正确

#https://cloud.tencent.com/developer/article/1629932
while getopts ":h" optname
do
    case "$optname" in
      "h")
        echo "#将coord.inc和DIMER_VECTOR的振动模式可视化
#以确认dimer算法的优化目标是否正确"
	exit
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        ;;
      "?")
        echo "Unknown option $OPTARG"
        ;;
      *)
        echo "Unknown error while processing options"
        ;;
    esac
    #echo "option index is $OPTIND"
done

first_line=`sed -n 6p POSCAR`
sed -i "1c $first_line" POSCAR
sed -n '1,7p' POSCAR > CENTCAR
echo "Selective Dynamics" >> CENTCAR
echo "Cartesian" >> CENTCAR

cat coord.inc | awk -va=2 -vb=3 -vc=4 '{print $a,$b,$c}' | sed 's/$/& T T T/g' >> CENTCAR
#(echo 406; echo 3; echo CENTCAR; echo 4062) | vaspkit | grep 123
#cp CENTCAR_REV CENTCAR 
#GetCP2KDimerVector.py cp2k-1.restart #Get NEWMODECAR
dimmode.pl CENTCAR DIMER_VECTOR 16 1
sz dimmode.xyz
